spring.datasource.url=jdbc:h2:mem:cocodedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD:secret_placeholder}

# Tells Hibernate to build your SQL tables automatically from RoomEntity.java
spring.jpa.hibernate.ddl-auto=update

# Turns on the browser console web switches
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console